### ISSUE TITLE
Most character models load up weirdly in newer versions

### ISSUE THREAD

**Issue by EntropyRequiem** [Aeven-Dev/UnityScnTool#1]
https://cdn.discordapp.com/attachments/844917055773212722/1023484762997936228/unknown.png

https://cdn.discordapp.com/attachments/844917055773212722/1023484281286303774/unknown.png

**Comment by Aeven-Dev** [comment]
Seems to be working properly!

![imagen](https://user-images.githubusercontent.com/106709979/193940796-bb3af6ff-5005-4d93-aae3-ed7f145924e2.png)

:D
