### ISSUE TITLE
Lightmap issues

### ISSUE THREAD

**Issue by EntropyRequiem** [Aeven-Dev/UnityScnTool#3]
http://i.epvpimg.com/daQUfab.jpg
http://i.epvpimg.com/UBBqbab.jpg
http://i.epvpimg.com/sG2Rfab.jpg

I'm confused myself. Ever since the addition of the lightmap feature I can't test stuff properly because things flicker around and adding random existing lightmaps as a placeholder to circumvent this also doesn't help most of the time.

**Comment by Aeven-Dev** [comment]
I have identified the issue, it was due to some probuilder compatibility stuff, but i think i have fixed it, before launching it i'll make sure to test it a couple of time!

Thanks for informing me! <3

**Comment by Aeven-Dev** [comment]
I think it's Fixed, Let me know if you find anything else!

**Comment by Aeven-Dev** [comment]
For now, i'll be closing this issue, if anyone has lightmap issues please open a new one ^
