### ISSUE TITLE
Renderflag 'Flare' is no longer working properly

### ISSUE THREAD

**Issue by EntropyRequiem** [Aeven-Dev/UnityScnTool#4]
Exported with current version:
http://i.epvpimg.com/uI0oaab.jpg
https://i.epvpimg.com/pxP9fab.jpg

Those gates with orange tinted windows are copied from my other map 'Central Station', which I last exported with a pre-lightmap feature version.
http://i.epvpimg.com/A20ecab.jpg
http://i.epvpimg.com/C9xyfab.jpg

Exported with a pre-lightmap feature version:
http://i.epvpimg.com/JndBfab.jpg
http://i.epvpimg.com/D8b6gab.jpg

I highly assume that other renderflags also don't work as intended.

**Comment by Aeven-Dev** [comment]
Since this issue might be related to #3 I would love to have an update on this one.

Thank you so much for taking the time to help me make my tool better <3

**Comment by EntropyRequiem** [comment]
It mostly works but I suppose, as of right now, current issues stem from having lightmaps applied to the object.

https://cdn.discordapp.com/attachments/844917055773212722/1026445213956329482/S4_20221003_124644.jpg
^Left window doesn't look good while middle and right one look fine, BUT they look different than before

**Comment by EntropyRequiem** [comment]
I posted an update to this on #3 since it likely is tied to lightmaps.

**Comment by Aeven-Dev** [comment]
im gonna asume the issue was the flar object, having broken lightmaps, which made it render black, and then the flare flag causing the flag to be completely transparent, lightmaps are working as of now, so if any new problems happens it would be better in a new issue ^^
