### ISSUE TITLE
Weapon Line doesn't line up when importing and exporting weapons without changing anything

### ISSUE THREAD

**Issue by notverr** [Aeven-Dev/UnityScnTool#5]
![brokenbat](https://user-images.githubusercontent.com/114446951/192477191-5dbc63ba-4f08-4812-99f5-4aa64170bbdc.png)
normal left, broken right
![batun](https://user-images.githubusercontent.com/114446951/192477776-dd65d52d-3123-426e-9a13-ee6efd538c49.png)
The top bat is the freshly imported one
The bottom bat is the exported one reopened (I moved it down a bit to not have them overlap, but that was the only change I did after reopening it.

**Comment by Aeven-Dev** [comment]
Ok i think it's fixed, a little missmatch between importing and exporting in diferent spaces, local and global

**Comment by notverr** [comment]
appears to be fixed, but the other bug I reported may be related to that
