### ISSUE TITLE
"CharacterLoader" don't root any S4 folder, is buged?

### ISSUE THREAD

**Issue by Sh4De4an0m** [Aeven-Dev/UnityScnTool#7]
![unityframe](https://user-images.githubusercontent.com/86963857/201537266-ce46a6f1-eff1-4f1b-b6fe-931a3f875dbf.PNG)
I have totally extracted Season 1 (FumbiClient) and Season 10 (EU 1379) but the script can't found "item.x7" in xml Folder, but "Load all maaaps" find "mapinfo" correctly, help me pls x.x

*Extracted with: Netsphere Explorer
*I tryed S4 main folder and all folders with " ".x7 inside.

**Comment by Aeven-Dev** [comment]
it should be the main folder, i'll update the message to specify the route is looking for

**Comment by Sh4De4an0m** [comment]
![ErrorOfKey](https://user-images.githubusercontent.com/86963857/202256235-1e14ff2e-3653-4dc2-8ae8-2be3eacbdbfc.PNG)
Well, I have managed to get around the problem with the folder by editing the code saying: 
**_`path = "E:\\S4Client";`_** and the script runs.
Now I get the error (in the image) related to the item keys, as if something was corrupted.
The base structure of the character "male_bip.scn" if it creates it before giving the error.
I'm going to try extracting another version but I don't think it will work
Any idea of what step I should follow? :/

**Comment by Aeven-Dev** [comment]
Gosh, did you update? those seem like old errors
