### ISSUE TITLE
Character SCN loads bones without meshes

### ISSUE THREAD

**Issue by CrownLimit** [Aeven-Dev/UnityScnTool#8]
Loading the Chaser SCN of Ophelia only loads in her bones and their animations, but no rendered meshes
![unity](https://user-images.githubusercontent.com/118738953/203057762-071d5646-95b3-485c-b2b9-6413724a5326.png)

Using other tools to view the contents of SCN files shows there are meshes (SCN Tool)
![scntool](https://user-images.githubusercontent.com/118738953/203058510-e7433bad-4b36-4be1-bbe5-597b8ebdea9f.png)

(Exported from SCN Tool as OBJ into Blender)
![Blender](https://user-images.githubusercontent.com/118738953/203058651-7a50d760-2017-4173-a7b4-8a20ec0336da.png)

I didnt come across any other file that has this issue at the time of writing this

**Comment by Aeven-Dev** [comment]
Would you kindly give me the output of the exception that was thrown? I can see in unity you have an error and it would help me knowing what it says

**Comment by CrownLimit** [comment]
here is the Exception it gives out in the Console
![Exception](https://user-images.githubusercontent.com/118738953/203426076-86178059-483b-4027-a53a-4916b483c85e.png)


The Exception comes up when it tries to load a Mesh that calls for a specific Texture.
In the Append window when i deselect certain meshes, it loads more bones and a mesh that has no issue loading its Texture, but then stops at the next Mesh that tries to load the specific Texture.

**Comment by Aeven-Dev** [comment]
yeah i solved the issue, silly me. All scn files always say tga but the texture ends up being dds, so i first asumed that was the case always, then some textures were actually dds so i did a simple change to have that covered but i didnt expect a scn file to say dds and then the file also be dds. x3 so silly of me.

**Comment by CrownLimit** [comment]
This update seemed to have fixed the issue
Thanks a lot and thanks for your work in general, you have no idea how much it helped me!
